apiVersion: v1
kind: Service
metadata:
  name: weatherly-frontend-service
spec:
  selector:
    app: weatherly-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer  # For Docker Desktop K8s, this will expose via localhost
